apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - horizontal-pod-autoscaler.yaml
  - virtual-service.yaml

commonLabels:
  app: "${SERVICE_NAME}"
